Fix check_oldest_idlexact to use state_change
OPMDG/check_pgactivity pull request #311
Opened 2022-05-03 19:05 UTC by frost242

Fix check_oldest_idlexact to use state_change instead of xact_start to
calculate the idle time. The previous behavior leads to warn for active
long transaction.

2022-05-03 19:05 UTC, frost242 commented
This fixes issue  #306

2022-05-03 19:14 UTC, frost242 commented
Please wait until tomorrow afternoon, I want to make an extensive test of this at work.

2022-05-04 08:58 UTC, frost242 commented
In a next PR

2022-05-04 09:22 UTC, ioguix requested changes
It deserve some user facing documentation explaining the diff between the what alert triggers on before/after 9.2, where `state_change` appears.

Plus, could you add `fix #306` in the commit message?

Thanks

2022-05-04 11:26 UTC, frost242 commented
Some documentation added, but I'm not very happy with the result. Do you have a better wording ?
If OK, I'll squash commit and add reference for this issue.

2022-05-04 15:06 UTC, ioguix commented on check_pgactivity
> +Thus, the service can wrongly can take account of transaction transciently in
```suggestion
Thus, the service can wrongly take account of transaction transiently in
```

2022-05-04 15:06 UTC, ioguix commented on check_pgactivity
> +From 9.2 and up, the service checks for transaction that had no activity since
```suggestion
From 9.2 and up, the service checks for transaction that really had no activity since
```

2022-05-05 11:35 UTC, frost242 commented
A bit better I think. Thought ?

2022-05-10 14:57 UTC, frost242 commented
Is that better ?

2022-05-10 15:04 UTC, ioguix approved these changes

2022-05-10 15:05 UTC, merged